## Fake internship and job detection system (ml and nlp)

In [2]:
import pandas as pd
df = pd.read_csv("fake_job_postings.csv")

In [3]:
 df.shape

(17880, 18)

In [4]:
df.isnull().sum()

job_id                     0
title                      0
location                 346
department             11547
salary_range           15012
company_profile         3308
description                1
requirements            2696
benefits                7212
telecommuting              0
has_company_logo           0
has_questions              0
employment_type         3471
required_experience     7050
required_education      8105
industry                4903
function                6455
fraudulent                 0
dtype: int64

In [5]:
df.head(5)

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0

In [6]:
required_columns = [
    'title',
    'company_profile',
    'description',
    'requirements',
    'benefits',
    'fraudulent'
]

df_s = df[required_columns]

In [7]:
df_s.shape

(17880, 6)

In [8]:
df_s.head(5)

,title,company_profile,description,requirements,benefits,fraudulent
0,Marketing Intern,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0
1,Customer Service - Cloud Video Production,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0
2,Commissioning Machinery Assistant (CMA),Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0
3,Account Executive - Washington DC,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0
4,Bill Review Manager,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0

In [9]:
df_s.isnull().sum()

title                 0
company_profile    3308
description           1
requirements       2696
benefits           7212
fraudulent            0
dtype: int64

In [10]:
text_cols = [
    'title',
    'company_profile',
    'description',
    'requirements',
    'benefits'
]

for col in text_cols:
    df_s[col] = df_s[col].fillna('')

C:\Users\ancha\AppData\Local\Temp\ipykernel_7612\1749752647.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_s[col] = df_s[col].fillna('')

In [11]:
df_s.isnull().sum()

title              0
company_profile    0
description        0
requirements       0
benefits           0
fraudulent         0
dtype: int64

In [12]:
df_s['combined_text'] = (
    df_s['title'] + ' ' +
    df_s['company_profile'] + ' ' +
    df_s['description'] + ' ' +
    df_s['requirements'] + ' ' +
    df_s['benefits'])

C:\Users\ancha\AppData\Local\Temp\ipykernel_7612\867639728.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_s['combined_text'] = (

In [13]:
df_s[['combined_text', 'fraudulent']].head(3)

                                       combined_text  fraudulent
0  Marketing Intern We're Food52, and we've creat...           0
1  Customer Service - Cloud Video Production 90 S...           0
2  Commissioning Machinery Assistant (CMA) Valor ...           0

In [14]:
df_s['combined_text'][0]

"Marketing Intern We're Food52, and we've created a groundbreaking and award-winning cooking site. We support, connect, and celebrate home cooks, and give them everything they need in one place.We have a top editorial, business, and engineering team. We're focused on using technology to find new and better ways to connect people around their specific food interests, and to offer them superb, highly curated information about food and cooking. We attract the most talented home cooks and contributors in the country; we also publish well-known professionals like Mario Batali, Gwyneth Paltrow, and Danny Meyer. And we have partnerships with Whole Foods Market and Random House.Food52 has been named the best food website by the James Beard Foundation and IACP, and has been featured in the New York Times, NPR, Pando Daily, TechCrunch, and on the Today Show.We're located in Chelsea, in New York City. Food52, a fast-growing, James Beard Award-winning online food community and crowd-sourced and curated recipe hub, is currently interviewing full- and part-time unpaid interns to work in a small team of editors, executives, and developers in its New York City headquarters.Reproducing and/or repackaging existing Food52 content for a number of partner sites, such as Huffington Post, Yahoo, Buzzfeed, and more in their various content management systemsResearching blogs and websites for the Provisions by Food52 Affiliate ProgramAssisting in day-to-day affiliate program support, such as screening affiliates and assisting in any affiliate inquiriesSupporting with PR &amp; Events when neededHelping with office administrative work, such as filing, mailing, and preparing for meetingsWorking with developers to document bugs and suggest improvements to the siteSupporting the marketing and executive staff Experience with content management systems a major plus (any blogging counts!)Familiar with the Food52 editorial voice and aestheticLoves food, appreciates the importance of home cooking and cooking with the seasonsMeticulous editor, perfectionist, obsessive attention to detail, maddened by typos and broken links, delighted by finding and fixing themCheerful under pressureExcellent communication skillsA+ multi-tasker and juggler of responsibilities big and smallInterested in and engaged with social media like Twitter, Facebook, and PinterestLoves problem-solving and collaborating to drive Food52 forwardThinks big picture but pitches in on the nitty gritty of running a small company (dishes, shopping, administrative support)Comfortable with the realities of working for a startup: being on call on evenings and weekends, and working long hours "

In [15]:
df_s['combined_text'][2]

"Commissioning Machinery Assistant (CMA) Valor Services provides Workforce Solutions that meet the needs of companies across the Private Sector, with a special focus on the Oil &amp; Gas Industry.\xa0Valor Services will be involved with you throughout every step of the hiring process and remain in contact with you all the way through the final step of signing of the employment contract with your new employer.\xa0Valor Services was founded with the vision of employing the unique skills, experiences, and qualities of America’s finest veterans to provide Private Sector companies with precise and concerted value-added services – and America’s finest Veterans with an optimized career opportunity.We are eager to get the word out to veterans that there are ample opportunities for employment in the private sector and that you are the ideal candidates to fill those positions.\xa0Valor Services\xa0Your Success is Our Mission.\xa0™\xa0 Our client, located in Houston, is actively seeking an experienced Commissioning Machinery Assistant that possesses strong supervisory skills and has an attention to detail. A strong dedication to safety is a must. The ideal candidate will execute all activities while complying with quality requirements and health, environmental, and safety regulations. Implement pre-commissioning and commissioning procedures for rotary equipment.Execute all activities with subcontractor’s assigned crew that pertains to the discipline.Ensure effective utilization of commissioning manpower and consumables.Ensure the execution of vendor specialists' field activities with the assigned resources from the sub-contractor per vendor’s representative plans.Carry out equipment inspections with client representatives and ensure proper certification is produced.Prepare forms for all pending tests and submit signed certificates for final hand over to the certification engineer for QA and QC.Coordinate in the field with vendor representatives.Keep records of all activities.Ensure that safety practices are strictly followed during the execution of activities.Report progress and constraints to the mechanical supervisor.Possible authorization by site manager to receive or issue a Permit To Work according to project Permit To Work procedures.Assist supervisor to expedite pending punch-list items in accordance with the commissioning manager’s priorities.Assist supervisor to coordinate and supervise construction-support activities during pre-commissioning and commissioning activities.Company Overview:Our client is a premiere engineering, construction, and procurement company that executes large-scale projects internationally. "

## NLP

In [16]:
df_lower=df_s['combined_text'].str.lower()

In [17]:
df_lower.loc[0]

"marketing intern we're food52, and we've created a groundbreaking and award-winning cooking site. we support, connect, and celebrate home cooks, and give them everything they need in one place.we have a top editorial, business, and engineering team. we're focused on using technology to find new and better ways to connect people around their specific food interests, and to offer them superb, highly curated information about food and cooking. we attract the most talented home cooks and contributors in the country; we also publish well-known professionals like mario batali, gwyneth paltrow, and danny meyer. and we have partnerships with whole foods market and random house.food52 has been named the best food website by the james beard foundation and iacp, and has been featured in the new york times, npr, pando daily, techcrunch, and on the today show.we're located in chelsea, in new york city. food52, a fast-growing, james beard award-winning online food community and crowd-sourced and curated recipe hub, is currently interviewing full- and part-time unpaid interns to work in a small team of editors, executives, and developers in its new york city headquarters.reproducing and/or repackaging existing food52 content for a number of partner sites, such as huffington post, yahoo, buzzfeed, and more in their various content management systemsresearching blogs and websites for the provisions by food52 affiliate programassisting in day-to-day affiliate program support, such as screening affiliates and assisting in any affiliate inquiriessupporting with pr &amp; events when neededhelping with office administrative work, such as filing, mailing, and preparing for meetingsworking with developers to document bugs and suggest improvements to the sitesupporting the marketing and executive staff experience with content management systems a major plus (any blogging counts!)familiar with the food52 editorial voice and aestheticloves food, appreciates the importance of home cooking and cooking with the seasonsmeticulous editor, perfectionist, obsessive attention to detail, maddened by typos and broken links, delighted by finding and fixing themcheerful under pressureexcellent communication skillsa+ multi-tasker and juggler of responsibilities big and smallinterested in and engaged with social media like twitter, facebook, and pinterestloves problem-solving and collaborating to drive food52 forwardthinks big picture but pitches in on the nitty gritty of running a small company (dishes, shopping, administrative support)comfortable with the realities of working for a startup: being on call on evenings and weekends, and working long hours "

In [18]:
df_lower.loc[1]

"customer service - cloud video production 90 seconds, the worlds cloud video production service.90 seconds is the worlds cloud video production service enabling brands and agencies to get high quality online video content shot and produced anywhere in the world. 90 seconds makes video production fast, affordable, and all managed seamlessly in the cloud from purchase to publish. http://90#url_fbe6559afac620a3cd2c22281f7b8d0eef56a73e3d9a311e2f1ca13d081dd630#90 seconds removes the hassle, cost, risk and speed issues of working with regular video production companies by managing every aspect of video projects in a beautiful online experience. with a growing global network of over 2,000 rated video professionals in over 50 countries managed by dedicated production success teams in 5 countries, 90 seconds provides a 100% success guarantee.90 seconds has produced almost 4,000 videos in over 30 countries for over 500 global brands including some of the worlds largest including paypal, l’oreal, sony and barclays and has offices in auckland, london, sydney, tokyo and singapore.http://90#url_fbe6559afac620a3cd2c22281f7b8d0eef56a73e3d9a311e2f1ca13d081dd630#\xa0|\xa0http://90#url_e2ad0bde3f09a0913a486abdbb1e6ac373bb3310f64b1fbcf550049bcba4a17b#\xa0| http://90#url_8c5dd1806f97ab90876d9daebeb430f682dbc87e2f01549b47e96c7bff2ea17e#\xa0 organised - focused - vibrant - awesome!do you have a passion for customer service? slick typing skills? maybe account management? ...and think administration is cooler than a polar bear on a jetski? then we need to hear you!\xa0we are the cloud video production service and opperating on a glodal level. yeah, it's pretty cool. serious about\xa0delivering a world class product and excellent customer service.our rapidly expanding business is looking for a talented project manager to manage the successful delivery of video projects, manage client communications and drive the production process. work with some of the coolest brands on the planet and learn from a global team that are representing nz is a huge way!we are entering the next growth stage of our business and growing quickly internationally. \xa0therefore, the position is bursting with opportunity for the right person entering the business at the right time.\xa090 seconds, the worlds cloud video production service -\xa0http://90#url_fbe6559afac620a3cd2c22281f7b8d0eef56a73e3d9a311e2f1ca13d081dd630#90 seconds is the worlds cloud video production service enabling brands and agencies to get high quality online video content shot and produced anywhere in the world. fast, affordable, and all managed seamlessly in the cloud from purchase to publish.\xa090 seconds removes the hassle, cost, risk and speed issues of working with regular video production companies by managing every aspect of video projects in a beautiful online experience. \xa0with a growing network of over 2,000 rated video professionals in over 50 countries and dedicated production success teams in 5 countries guaranteeing video project success 100%. it's as easy as commissioning a quick google adwords campaign.90 seconds has produced almost 4,000 videos in over 30 countries for over 500 global brands including some of the worlds largest including paypal, l'oreal, sony and barclays and has offices in auckland, london, sydney, tokyo &amp; singapore.our auckland office is based\xa0right in the heart of the wynyard quarter innovation precinct - gridakl!\xa0 what we expect from you:your key responsibility will be to communicate with the client, 90 seconds team and freelance community throughout the video production process including, shoot planning, securing freelance talent, managing workflow and the online production management system. \xa0the aim is to manage each video project effectively so that we produce great videos that our clients love.key\xa0attributesclient focused\xa0- excellent customer service and communication skillsonline -\xa0oustanding computer knowledge and experience using online software and project management toolsorganised\xa0- manage workload and able to multi-task100% attention to detailmotivated -\xa0self-starter with a passion for doing excellent work and achieving great resultsadaptable\xa0- show initiative and think on your feet as this is a constantly evolving atmosphereflexible\xa0- fast turnaround work and after hours availabilityeasy going\xa0&amp; upbeat\xa0- dosen't get bogged down and loves the challengesense of humour\xa0- have a laugh and know that working in a startup takes guts!ability to deliver\xa0- including meeting project deadlines and budgetattitude is more important than experience at 90 seconds, however previous experience in customer service and/or project management is beneficialplease view our platform / website at\xa0#url_395a8683a907ce95f49a12fb240e6e47ad8d5a4f96d07ebbd869c4dd4dea1826#\xa0and get a clear understand about what we do before reaching out. what you will get from usthrough being part of the 90 seconds team you will gain:experience working on projects located around the world with an international brandexperience working with a variety of clients and on a large range of projectsopportunity to drive and grow production function and teama positive working environment with a great teampay$40,000-$55,000applying for this role with a videobeing a video business, we understand that one of the quickest ways that we can assess your suitability for this role, and one of the quickest ways that you can apply for it, is for you to submit a 60-90 second long video telling us about yourself, your experience and why you think you would be perfect for the role. \xa0it’s not about being a filmmaker or making a really creative video. \xa0a simple video filmed with a smart phone or web cam will be fine. please also include where you are based and when you can start.you can upload the video onto youtube or vimeo (or similar) as a draft or live link.applications due by 5pm on wednesday 18th july 2014 -\xa0once you have a video ready, apply for this role via the following link together with a cover letter and your cv.\xa0after we have watched your video and get an idea of your suitability for the role, we will email the shortlisted candidates"

In [20]:
import re

def remove_url(text):
    pattern = re.compile(r'https?://\S+|www\.\S+')
    return pattern.sub('', text)

In [21]:
df_no_url = df_lower.apply(remove_url)

In [22]:
df_no_url.loc[6]

"head of content (m/f) founded in 2009, the\xa0fonpit ag\xa0rose with its international web portal\xa0androidpit\xa0to the world's largest android community. every month over 18 million android and tech enthusiasts around the world log into\xa0androidpit\xa0, where they know they'll find the latest and most innovative information about android and android-apps in 6 different languages. our business activities consist of close collaboration with many of the world's largest tech, web and mobile companies.in 2014,\xa0app media\xa0amended fonpit ag’s brand portfolio. as a one-stop shop for app marketing,app media\xa0delivers quality performance marketing for apps to give clients the most successful campaigns possible with custom concepts and sustainable results.located in the heart of berlin, we are constantly looking for highly motivated and success driven personalities to help\xa0androidpit\xa0and\xa0app media\xa0grow even further. your responsibilities:\xa0manage the english-speaking editorial team and build a team of best-in-class editorsset up content creation schedules and ensure deadlines are adhered toresearch and write about the latest tech topics and news in relation to the android ecosystemensure that the content on the site is of a consistently high qualitybe the face and voice of #url_874846adb69d98865d05ec57ce2425d9e363ef71e0c8436e59e86a136a508716# your know-how:\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0 university or college degree in journalism, media or other communication studiesprofessional experience in relevant fields, e.g. online editorial, community management, tech writing…possession of contacts within key companies in the mobile industryexperience in leading &amp; motivating small teamspassion for the android world, honed writing skills with a personal flair, and willingness to share your android knowledgestrong commitment to success and a motivating and inspiring personality.comfortable in a dynamic startup environmentenglish native speakerlocated in berlin or surroundings your benefits:\xa0being part of a fast-growing company in a booming industryfast decision-making thanks to flat hierarchies and clear structuresfreedom to unfold your own ideas &amp; creativity and to take over responsibility right from the startcontinued growth in a successful, international team, which thrives in a familiar, but professional, working atmospherefree drinks, table tennis, lunch catering, feel good management, team events, office dogs and more"

In [23]:
import string
string.punctuation
exclude=string.punctuation

In [24]:
import string
def clean_text(text):
    text = text.replace('\xa0', ' ')
    text = text.replace('’', "'").replace('‘', "'")
    text = text.replace('“', '"').replace('”', '"')
    for char in exclude:
        text = text.replace(char, '')
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

In [25]:
df_clean_final = df_no_url.apply(clean_text)

In [26]:
df_clean_final.loc[6]

'head of content mf founded in 2009 the fonpit ag rose with its international web portal androidpit to the worlds largest android community every month over 18 million android and tech enthusiasts around the world log into androidpit where they know theyll find the latest and most innovative information about android and androidapps in 6 different languages our business activities consist of close collaboration with many of the worlds largest tech web and mobile companiesin 2014 app media amended fonpit ags brand portfolio as a onestop shop for app marketingapp media delivers quality performance marketing for apps to give clients the most successful campaigns possible with custom concepts and sustainable resultslocated in the heart of berlin we are constantly looking for highly motivated and success driven personalities to help androidpit and app media grow even further your responsibilities manage the englishspeaking editorial team and build a team of bestinclass editorsset up content creation schedules and ensure deadlines are adhered toresearch and write about the latest tech topics and news in relation to the android ecosystemensure that the content on the site is of a consistently high qualitybe the face and voice of url874846adb69d98865d05ec57ce2425d9e363ef71e0c8436e59e86a136a508716 your knowhow university or college degree in journalism media or other communication studiesprofessional experience in relevant fields eg online editorial community management tech writing…possession of contacts within key companies in the mobile industryexperience in leading amp motivating small teamspassion for the android world honed writing skills with a personal flair and willingness to share your android knowledgestrong commitment to success and a motivating and inspiring personalitycomfortable in a dynamic startup environmentenglish native speakerlocated in berlin or surroundings your benefits being part of a fastgrowing company in a booming industryfast decisionmaking thanks to flat hierarchies and clear structuresfreedom to unfold your own ideas amp creativity and to take over responsibility right from the startcontinued growth in a successful international team which thrives in a familiar but professional working atmospherefree drinks table tennis lunch catering feel good management team events office dogs and more'

In [27]:
df_clean_final.loc[0]

'marketing intern were food52 and weve created a groundbreaking and awardwinning cooking site we support connect and celebrate home cooks and give them everything they need in one placewe have a top editorial business and engineering team were focused on using technology to find new and better ways to connect people around their specific food interests and to offer them superb highly curated information about food and cooking we attract the most talented home cooks and contributors in the country we also publish wellknown professionals like mario batali gwyneth paltrow and danny meyer and we have partnerships with whole foods market and random housefood52 has been named the best food website by the james beard foundation and iacp and has been featured in the new york times npr pando daily techcrunch and on the today showwere located in chelsea in new york city food52 a fastgrowing james beard awardwinning online food community and crowdsourced and curated recipe hub is currently interviewing full and parttime unpaid interns to work in a small team of editors executives and developers in its new york city headquartersreproducing andor repackaging existing food52 content for a number of partner sites such as huffington post yahoo buzzfeed and more in their various content management systemsresearching blogs and websites for the provisions by food52 affiliate programassisting in daytoday affiliate program support such as screening affiliates and assisting in any affiliate inquiriessupporting with pr amp events when neededhelping with office administrative work such as filing mailing and preparing for meetingsworking with developers to document bugs and suggest improvements to the sitesupporting the marketing and executive staff experience with content management systems a major plus any blogging countsfamiliar with the food52 editorial voice and aestheticloves food appreciates the importance of home cooking and cooking with the seasonsmeticulous editor perfectionist obsessive attention to detail maddened by typos and broken links delighted by finding and fixing themcheerful under pressureexcellent communication skillsa multitasker and juggler of responsibilities big and smallinterested in and engaged with social media like twitter facebook and pinterestloves problemsolving and collaborating to drive food52 forwardthinks big picture but pitches in on the nitty gritty of running a small company dishes shopping administrative supportcomfortable with the realities of working for a startup being on call on evenings and weekends and working long hours'

In [118]:
from nltk.corpus import stopwords
stop = set(stopwords.words('english'))

In [119]:
def remove_stopwords(text):
    if not isinstance(text, str):
        return text   # NaN ya non-string ko as-it-is chhod do
    
    words = []
    for word in text.split():
        if word not in stop:
            words.append(word)
    
    return " ".join(words)

In [120]:
df_no_stopword = df_clean_final.apply(remove_stopwords)

In [121]:
df_no_stopword.loc[0]

'marketing intern food52 weve created groundbreaking awardwinning cooking site support connect celebrate home cooks give everything need one placewe top editorial business engineering team focused using technology find new better ways connect people around specific food interests offer superb highly curated information food cooking attract talented home cooks contributors country also publish wellknown professionals like mario batali gwyneth paltrow danny meyer partnerships whole foods market random housefood52 named best food website james beard foundation iacp featured new york times npr pando daily techcrunch today showwere located chelsea new york city food52 fastgrowing james beard awardwinning online food community crowdsourced curated recipe hub currently interviewing full parttime unpaid interns work small team editors executives developers new york city headquartersreproducing andor repackaging existing food52 content number partner sites huffington post yahoo buzzfeed various content management systemsresearching blogs websites provisions food52 affiliate programassisting daytoday affiliate program support screening affiliates assisting affiliate inquiriessupporting pr amp events neededhelping office administrative work filing mailing preparing meetingsworking developers document bugs suggest improvements sitesupporting marketing executive staff experience content management systems major plus blogging countsfamiliar food52 editorial voice aestheticloves food appreciates importance home cooking cooking seasonsmeticulous editor perfectionist obsessive attention detail maddened typos broken links delighted finding fixing themcheerful pressureexcellent communication skillsa multitasker juggler responsibilities big smallinterested engaged social media like twitter facebook pinterestloves problemsolving collaborating drive food52 forwardthinks big picture pitches nitty gritty running small company dishes shopping administrative supportcomfortable realities working startup call evenings weekends working long hours'

## now, modelling using TF-IDF

In [122]:
x=df_no_stopword
y=df['fraudulent']

In [132]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=42, stratify=y)

In [133]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf=TfidfVectorizer(max_features=5000,
                      ngram_range=(1,2),
                     )
x_train_tfidf=tfidf.fit_transform(x_train)
x_test_tfidf=tfidf.transform(x_test)

## logistic regression

In [134]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(
    max_iter=1000,
    class_weight={0:1, 1:2}
)

model.fit(x_train_tfidf, y_train)

LogisticRegression(class_weight={0: 1, 1: 2}, max_iter=1000)

In [135]:
from sklearn.metrics import accuracy_score, classification_report

y_pred = model.predict(x_test_tfidf)

print("Accuracy:", accuracy_score(y_test, y_pred))
print(classification_report(y_test, y_pred))

Accuracy: 0.9784675615212528
              precision    recall  f1-score   support

           0       0.98      1.00      0.99      3403
           1       0.94      0.59      0.73       173

    accuracy                           0.98      3576
   macro avg       0.96      0.79      0.86      3576
weighted avg       0.98      0.98      0.98      3576

In [136]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred)
print(cm)

[[3397    6]
 [  71  102]]

## svm

In [137]:
from sklearn.svm import LinearSVC

model = LinearSVC(
    class_weight={0:1, 1:2}
)

model.fit(x_train_tfidf, y_train)

LinearSVC(class_weight={0: 1, 1: 2})

In [138]:
y_pred = model.predict(x_test_tfidf)

In [139]:
from sklearn.metrics import confusion_matrix, accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

Accuracy: 0.985178970917226
[[3391   12]
 [  41  132]]

In [140]:
from sklearn.metrics import classification_report

y_pred = model.predict(x_test_tfidf)

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99      3403
           1       0.92      0.76      0.83       173

    accuracy                           0.99      3576
   macro avg       0.95      0.88      0.91      3576
weighted avg       0.98      0.99      0.98      3576